### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by kotarusv** [AATHITH/kubesort#4]
I stumbles across this tool today and seems very useful. I started using it for pods, deployments, and services. Can you incorporate other objects as well? This tool helps a lot for cluster cleaning and troubleshooting.

Thanks for the good work.

**Comment by AATHITH** [comment]
Thanks for your feedback, @kotarusv Will try to add those other objects as soon as possible.
🤓Happy to see that someone is making use of my project.

**Comment by kotarusv** [comment]
Thanks for ack and helping here. when shall I accept? am looking for all objects types ( like projects, PVC, PV, routers, pods, jobs, etc)
